export enum CategoryEvent {
  ATHLETICS = 'ATHLETICS',
  BASKETBALL = 'BASKETBALL',
  CYCLING = 'CYCLING',
  FOOTBALL = 'FOOTBALL',
  GYMNASTICS = 'GYMNASTICS',
  SWIMMING = 'SWIMMING',
  TENNIS = 'TENNIS',
  VOLLEYBALL = 'VOLLEYBALL'
}
